version: "3.7"
services:
  webapp:
    image: ceuph/yii2-php:sqlsrv
    volumes:
      - .:/app
      - ./index.php:/app/web/index.php
      - ./.htaccess:/app/web/.htaccess
      - ./themes:/app/web/themes
      - ./assets:/app/web/assets
    ports:
      - 4004:80